# Generated by Django 5.1.3 on 2025-02-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_applicationtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtype',
            name='image',
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
